/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-fits_sink
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_FITS_SINK_API_H
#define INCLUDED_FITS_SINK_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_fits_sink_EXPORTS
#define FITS_SINK_API __GR_ATTR_EXPORT
#else
#define FITS_SINK_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FITS_SINK_API_H */
